#!/bin/bash
export ZERO_AR_DATE=1
export SOURCE_DATE_EPOCH=0

NATIVE_TESTS=$NATIVE_TESTS

# List of dependencies that should be rebuilt.
# If you specify dependency source that doesn't change (local directory)
# add this dependency there so new files are copied during a build.
reactive_deps=(
    nativecrypto
)

set -u
set -e

echo Build Started
date

if [ Darwin = $(uname -s) ]; then
    MACOSV=$(sw_vers -productVersion)
    XCODEV=$(xcodebuild -version)

    echo "macOS $MACOSV - $XCODEV"
fi

# Pick up the current directory:
CURRENT_DIR=$(pwd)
export BUILD_DIR=$CURRENT_DIR/native-libs/deps/build
#if [ -z ${BUILD_DIR+x} ]; then
#  export BUILD_DIR=${BUILD_DIR:-$CURRENT_DIR/native-libs/deps/build};
#fi

# Do the build:

for dep in "${reactive_deps[@]}"; do
    touch native-libs/deps/recipes/$dep/$dep.recipe
done

(
    targets=""

    if [[ "$NATIVE_TESTS" -eq "1" ]]; then
        targets="$targets nativecrypto.build-native"
    else
        if [ Darwin = $(uname -s) ]; then
            targets="$targets nativecrypto.package-ios-universal"
        fi

        targets="$targets nativecrypto.build-android-arm"
        targets="$targets nativecrypto.build-android-arm64"
        targets="$targets nativecrypto.build-android-x86"
        targets="$targets nativecrypto.build-android-x86_64"
    fi

    cd native-libs/deps
    make $targets $@
)

if [[ "$NATIVE_TESTS" -eq "1" ]]; then
    cd native-libs
    make check V=1 T=1
    echo "Finished running tests."
    exit 0
fi

# Copy the results locally:
if [ Darwin = $(uname -s) ]; then
    mkdir -m 0775 -p ios/Headers
    mkdir -m 0775 -p ios/Libraries
    cp -aL $BUILD_DIR/nativecrypto/nativecrypto-ios-universal/include/* ios/Headers
    cp -a $BUILD_DIR/nativecrypto/nativecrypto-ios-universal/lib/* ios/Libraries
fi

BASE="./android"
JNI_DIR="$BASE/jni"
JNI_BUILD_DIR="$JNI_DIR/libs"
ANDROID_PATH="$BASE/src/main"

rm -rf $JNI_BUILD_DIR
mkdir -p $JNI_BUILD_DIR/includes
mkdir -p $JNI_BUILD_DIR/armeabi-v7a
mkdir -p $JNI_BUILD_DIR/arm64-v8a
mkdir -p $JNI_BUILD_DIR/x86
mkdir -p $JNI_BUILD_DIR/x86_64

# Copy & fix header:
cp native-libs/src/native-crypto.h $JNI_BUILD_DIR/includes
sed  -e 's/const char *\*/const char *const /' $JNI_BUILD_DIR/includes/native-crypto.h \
    > $JNI_BUILD_DIR/includes/native-crypto-const.h

# Copy Android libraries:
copy_so() {
    echo cp $BUILD_DIR/nativecrypto/android-$1/libnativecrypto.so $JNI_BUILD_DIR/$2/
    cp $BUILD_DIR/nativecrypto/android-$1/libnativecrypto.so $JNI_BUILD_DIR/$2/
}
copy_so arm armeabi-v7a
copy_so arm64 arm64-v8a
copy_so x86 x86
copy_so x86_64 x86_64

echo Build Finished
date
