name: PR Rebase
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Rebase
    if: >-
      github.event.issue.pull_request != '' && 
      (
        contains(github.event.comment.body, '/autosquash') || 
        contains(github.event.comment.body, '/fixup') ||
        contains(github.event.comment.body, '/rebase')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: samholmes/rebase@1.7
        with:
          autosquash: ${{ true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
